### ISSUE TITLE
SyntaxError: invalid regexp group in Firefox

### ISSUE THREAD

**Issue by codygman** [grin-compiler/haskell-code-spot#3]
Hi! I just tried out the instructions from the readme and I get "invalid regexp group" as of 222911a8897b40f6376d684d7bf9581e82334a94.

I successfully ran haskell-code-spot on my laptop some time ago at commit 429f2a37ba6b9e84f9c068e3a32948beacdd4c67 and it worked.

Maybe I have the wrong npm version or something? I thought npm sorts all of that out, but maybe I am mistaken.

possibly related: https://github.com/sindresorhus/ip-regex/issues/24

**Comment by csabahruska** [comment]
Ok, what is your Firefox version?
It works with Firefox 80.0 (64-bit linux).

**Comment by codygman** [comment]
I'm not sure how this is possible, but apparently I'm on firefox 69 :S 

I'll just close this one, lol.
